import type { Server, Socket } from "socket.io";
import { COIN_SCALE, type ClientToServerEvents, type GameRoom, type GameType, type HwatuCard, type RoomPhase, type ServerToClientEvents, type SutdaActionCommand, type SutdaRoomSnapshot, type SutdaSeatCommand, type SutdaSeatSnapshot, type SutdaStreet, type SutdaWinnerSnapshot } from "@golden/contracts";
import { evaluateSutdaHand, resolveSutdaWinners, shuffleSutdaDeck } from "@golden/game-core";
import type { AuthUser } from "../../auth/auth.js";
import { pool } from "../../database/pool.js";
import { walletService } from "../../wallet/wallet-service.js";
import { sutdaService } from "../sutda/sutda-service.js";

type GoldenServer = Server<ClientToServerEvents, ServerToClientEvents, Record<string, never>, { user: AuthUser }>;
type GoldenSocket = Socket<ClientToServerEvents, ServerToClientEvents, Record<string, never>, { user: AuthUser }>;
interface RoomRow { id: string; game_type: GameType; code: string; name: string; min_bet: number; max_bet: number; enabled: boolean }
interface Seat { userId: string; username: string; folded: boolean; street: number; total: number; cards: HwatuCard[] }
const SEATS = 6, ACTION_MS = 20_000, DEAL_MS = 900, RESULT_MS = 5_000;
const delay = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

class SutdaRoomActor {
  private phase: RoomPhase = "WAITING"; private phaseEndsAt: string | null = null; private roundId: string | null = null; private sequence = 0;
  private street: SutdaStreet | null = null; private seats: Array<Seat | null> = Array.from({ length: SEATS }, () => null); private ready = new Set<string>(); private sittingOut = new Set<string>();
  private participants = new Map<string, Set<string>>(); private names = new Map<string, string>(); private dealer = 0; private acting: number | null = null; private currentBet = 0; private acted = new Set<number>(); private requests = new Set<string>(); private turnResolve: (() => void) | null = null; private cycleRunning = false; private token = 0; private paused = false; private winners: SutdaWinnerSnapshot[] = [];
  constructor(private readonly io: GoldenServer, readonly room: RoomRow) {}
  get playerCount() { return this.participants.size; } private get seatedCount() { return this.seats.filter(Boolean).length; } private get channel() { return `sutda-room:${this.room.id}`; }
  publicRoom(): GameRoom { return { id: this.room.id, gameType: this.room.game_type, code: this.room.code, name: this.room.name, minBet: this.room.min_bet, maxBet: this.room.max_bet, playerCount: this.playerCount, phase: this.phase, enabled: this.room.enabled, paused: this.paused }; }
  setPaused(value: boolean) { this.paused = value; if (!value) this.launch(); } hasSocket(id: string) { return [...this.participants.values()].some((ids) => ids.has(id)); } hasParticipant(userId: string) { return this.participants.has(userId); } participantUserIds(): string[] { return [...this.participants.keys()]; }
  async join(socket: GoldenSocket): Promise<SutdaRoomSnapshot> { const user = socket.data.user; const ids = this.participants.get(user.id) ?? new Set<string>(); ids.add(socket.id); this.participants.set(user.id, ids); this.names.set(user.id, user.nickname); this.sittingOut.delete(user.id); await socket.join(this.channel); this.presence(); return this.snapshot(user.id); }
  async leave(socket: GoldenSocket) { const userId = socket.data.user.id; const ids = this.participants.get(userId); ids?.delete(socket.id); if (!ids?.size) { this.participants.delete(userId); this.sittingOut.add(userId); } await socket.leave(this.channel); this.presence(); }
  async sit(userId: string, input: SutdaSeatCommand) { if (!this.hasParticipant(userId)) throw new Error("ROOM_JOIN_REQUIRED"); if (this.seats.some((seat) => seat?.userId === userId)) throw new Error("ALREADY_SEATED"); const index = input.seatNumber - 1; if (index < 0 || index >= SEATS || this.seats[index]) throw new Error("SEAT_TAKEN"); if (await walletService.getUserBalance(userId) < this.room.min_bet * 2) throw new Error("INSUFFICIENT_BALANCE"); this.seats[index] = { userId, username: this.names.get(userId) ?? "player", folded: false, street: 0, total: 0, cards: [] }; this.sequence++; await this.emit(); return this.snapshot(userId); }
  async standUp(userId: string) { const index = this.seats.findIndex((seat) => seat?.userId === userId); if (index < 0) throw new Error("NOT_SEATED"); if (this.roundId) { this.sittingOut.add(userId); } else this.seats[index] = null; this.ready.delete(userId); this.sequence++; await this.emit(); return this.snapshot(userId); }
  async setReady(userId: string, value: boolean) { if (!this.seats.some((seat) => seat?.userId === userId)) throw new Error("NOT_SEATED"); value ? this.ready.add(userId) : this.ready.delete(userId); this.sequence++; await this.emit(); if (value) this.launch(); return this.snapshot(userId); }
  async act(userId: string, input: SutdaActionCommand) { if (this.requests.has(input.requestId)) return this.snapshot(userId); this.requests.add(input.requestId); let done = false; try { const index = this.seats.findIndex((seat) => seat?.userId === userId); if (index < 0) throw new Error("NOT_SEATED"); if (this.phase !== "PLAYER_TURN" || input.roundId !== this.roundId || this.acting !== index + 1) throw new Error("NOT_YOUR_TURN"); await this.apply(index, input.action); done = true; this.sequence++; await this.emit(); this.turnResolve?.(); return this.snapshot(userId); } finally { if (!done) this.requests.delete(input.requestId); } }
  private async apply(index: number, action: SutdaActionCommand["action"]) { const seat = this.seats[index]!; const toCall = this.currentBet - seat.street; if (action === "die") { seat.folded = true; await sutdaService.markFolded(this.roundId!, seat.userId); return; } if (action === "check") { if (toCall) throw new Error("MUST_CALL_OR_DIE"); this.acted.add(index); return; } const balance = await walletService.getUserBalance(seat.userId); if (action === "call") { if (balance < toCall) throw new Error("INSUFFICIENT_BALANCE"); if (toCall) await this.contribute(index, toCall); this.acted.add(index); return; } // "하프" raises by half the current pot (matching Hold'em's own half-pot convention — see
    // HoldemRoomPage's `half` preset), not half of the actor's own balance: sizing it off balance let a
    // deep-stacked player's single half inflate the pot far past what the pot itself justified.
    const potTotal = this.seats.reduce((sum, s) => sum + (s?.total ?? 0), 0); const desiredRaise = Math.max(this.room.min_bet, Math.round(potTotal / 2)); const headroom = this.room.max_bet - seat.total - toCall; const raiseBy = Math.min(desiredRaise, Math.max(0, headroom)); if (raiseBy <= 0) throw new Error("TABLE_LIMIT_REACHED"); const addition = toCall + raiseBy; if (balance < addition) throw new Error("INSUFFICIENT_BALANCE"); const target = seat.street + addition; await this.contribute(index, addition); this.currentBet = target; this.acted = new Set([index]); }
  private async contribute(index: number, coins: number) { const seat = this.seats[index]!; if (seat.total + coins > this.room.max_bet) throw new Error("TABLE_LIMIT_REACHED"); const client = await pool.connect(); try { await client.query("BEGIN"); await sutdaService.contribute(client, { requestId: `${this.roundId}:${seat.userId}:${seat.total}`, userId: seat.userId, roomId: this.room.id, roundId: this.roundId!, seatNumber: index + 1, amountMinor: coins * COIN_SCALE }); await client.query("COMMIT"); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } seat.street += coins; seat.total += coins; }
  async snapshot(userId: string): Promise<SutdaRoomSnapshot> { const mine = this.seats.findIndex((seat) => seat?.userId === userId); const reveal = this.street === "showdown"; const seats: SutdaSeatSnapshot[] = await Promise.all(this.seats.map(async (seat, index) => !seat ? ({ seatNumber: index + 1, userId: null, username: null, stack: 0, streetContributed: 0, totalContributed: 0, folded: false, sittingOut: false, isDealer: false, isTurn: false, cards: null, handLabel: null, ready: false }) : ({ seatNumber: index + 1, userId: seat.userId, username: seat.username, stack: await walletService.getUserBalance(seat.userId), streetContributed: seat.street, totalContributed: seat.total, folded: seat.folded, sittingOut: this.sittingOut.has(seat.userId), isDealer: this.dealer === index + 1, isTurn: this.acting === index + 1, cards: seat.userId === userId || (reveal && !seat.folded) ? (seat.cards.length ? seat.cards : null) : null, handLabel: seat.cards.length === 2 && (seat.userId === userId || reveal) ? evaluateSutdaHand(seat.cards).label : null, ready: this.ready.has(seat.userId) }))); const me = mine >= 0 ? this.seats[mine] : null; return { room: this.publicRoom(), roundId: this.roundId, sequence: this.sequence, phaseEndsAt: this.phaseEndsAt, street: this.street, pot: { amount: this.seats.reduce((sum, seat) => sum + (seat?.total ?? 0), 0) }, seats, mySeatNumber: mine < 0 ? null : mine + 1, toCall: me ? Math.max(0, this.currentBet - me.street) : 0, actingSeat: this.phase === "PLAYER_TURN" ? this.acting : null, lastWinners: this.winners, walletBalance: await walletService.getUserBalance(userId) }; }
  private async emit() { for (const [userId, sockets] of this.participants) { const shot = await this.snapshot(userId); for (const id of sockets) this.io.to(id).emit("sutda.snapshot", shot); } }
  private presence() { this.io.emit("room.presence", { roomId: this.room.id, playerCount: this.playerCount }); }
  private async phaseTo(phase: RoomPhase, ms?: number) { this.phase = phase; this.phaseEndsAt = ms ? new Date(Date.now() + ms).toISOString() : null; this.sequence++; await this.emit(); }
  private allReady() { return this.seats.every((seat) => !seat || this.ready.has(seat.userId)); }
  private launch() { if (this.cycleRunning || this.paused || this.phase !== "WAITING" || this.seatedCount < 2 || !this.allReady()) return; this.cycleRunning = true; void this.play().catch(async (error) => { console.error(`Sutda room ${this.room.code} failed`, error); try { if (this.roundId) await sutdaService.refundRound(this.roundId, this.room.id); } catch (refundError) { console.error(`Sutda room ${this.room.code} refund failed`, refundError); } finally { this.reset(); await this.emit(); } }).finally(() => { this.cycleRunning = false; this.launch(); }); }
  private reset() { this.phase = "WAITING"; this.phaseEndsAt = null; this.roundId = null; this.street = null; this.acting = null; this.currentBet = 0; this.acted.clear(); this.requests.clear(); this.ready.clear(); for (const id of this.sittingOut) { const index = this.seats.findIndex((seat) => seat?.userId === id); if (index >= 0) this.seats[index] = null; } this.sittingOut.clear(); }
  private active() { return this.seats.map((seat, index) => seat && !seat.folded ? index + 1 : null).filter((value): value is number => value !== null); }
  private order(start: number) { const result: number[] = []; for (let i = 0; i < SEATS; i++) { const n = ((start - 1 + i) % SEATS) + 1; if (this.seats[n - 1] && !this.sittingOut.has(this.seats[n - 1]!.userId)) result.push(n); } return result; }
  private async play() { const token = ++this.token; const eligible = this.seats.map((seat, index) => seat && !this.sittingOut.has(seat.userId) ? index + 1 : null).filter((value): value is number => value !== null); if (eligible.length < 2) return; for (const number of eligible) { const seat = this.seats[number - 1]!; if (await walletService.getUserBalance(seat.userId) < this.room.min_bet * 2) this.sittingOut.add(seat.userId); } const order = this.order(this.dealer + 1); if (order.length < 2) return; this.dealer = order[0]!; for (const number of order) { const seat = this.seats[number - 1]!; seat.folded = false; seat.street = 0; seat.total = 0; seat.cards = []; } const next = await pool.query<{ next_number: string }>("SELECT COALESCE(MAX(round_number),0)+1 AS next_number FROM game_rounds WHERE room_id=$1", [this.room.id]); const created = await pool.query<{ id: string }>("INSERT INTO game_rounds (room_id,round_number,phase,rules_version) VALUES ($1,$2,'DEALING','sutda-v1') RETURNING id", [this.room.id, Number(next.rows[0]!.next_number)]); this.roundId = created.rows[0]!.id; this.winners = []; for (const number of order) await this.contribute(number - 1, this.room.min_bet); this.currentBet = this.room.min_bet; const deck = shuffleSutdaDeck(); for (const number of order) this.seats[number - 1]!.cards.push(deck.pop()!); this.street = "first"; await this.phaseTo("DEALING", DEAL_MS); await delay(DEAL_MS); await this.betting(order[1] ?? order[0]!, order, token); if (token !== this.token || this.active().length <= 1) return this.showdown(); for (const number of order) if (!this.seats[number - 1]!.folded) { this.seats[number - 1]!.cards.push(deck.pop()!); await sutdaService.recordCards(this.roundId, this.seats[number - 1]!.userId, this.seats[number - 1]!.cards); } for (const seat of this.seats) if (seat) seat.street = 0; this.currentBet = 0; this.acted.clear(); this.street = "final"; await this.phaseTo("DEALING", DEAL_MS); await delay(DEAL_MS); await this.betting(order[1] ?? order[0]!, order, token); await this.showdown(); await delay(RESULT_MS); this.reset(); this.sequence++; await this.emit(); }
  private async betting(first: number, order: number[], token: number) { this.street = this.street ?? "first"; this.acting = first; while (token === this.token && this.active().length > 1) { const seat = this.seats[this.acting - 1]!; if (seat.folded) { this.acting = this.next(this.acting, order); continue; } await this.phaseTo("PLAYER_TURN", ACTION_MS); const prompted = this.acting; await new Promise<void>((resolve) => { const timer = setTimeout(resolve, ACTION_MS); this.turnResolve = () => { clearTimeout(timer); resolve(); }; }); this.turnResolve = null; const late = this.seats[prompted - 1]!; if (!late.folded && !this.acted.has(prompted - 1) && this.acting === prompted) { if (this.currentBet > late.street) { late.folded = true; await sutdaService.markFolded(this.roundId!, late.userId); } else this.acted.add(prompted - 1); this.sequence++; await this.emit(); } if (this.active().length <= 1 || order.filter((n) => { const s = this.seats[n - 1]; return s && !s.folded && this.acted.has(n - 1) && s.street === this.currentBet; }).length === this.active().length) break; this.acting = this.next(prompted, order); } this.acting = null; }
  private next(from: number, order: number[]) { const index = order.indexOf(from); for (let step = 1; step <= order.length; step++) { const number = order[(index + step) % order.length]!; if (!this.seats[number - 1]!.folded) return number; } return from; }
  private async showdown() { if (!this.roundId) return; this.street = "showdown"; const active = this.seats.map((seat, index) => seat && !seat.folded ? { userId: seat.userId, cards: seat.cards, seatNumber: index + 1 } : null).filter((item): item is NonNullable<typeof item> => item !== null); // A single survivor always just wins outright — win-by-fold at either street. Routing this
    // through resolveSutdaWinners would let a lone "멍텅구리 구사" hand force a redeal with no one
    // left to redeal against, mislabeling a clean win and (via settle's takeRake=false) waiving the house rake.
    const earlyWin = active.length === 1; const result = earlyWin ? { winnerIds: [active[0]!.userId], handByUser: new Map<string, ReturnType<typeof evaluateSutdaHand>>(), redeal: false } : resolveSutdaWinners(active); const winnerIds = result.redeal ? active.map((item) => item.userId) : result.winnerIds; const settled = await sutdaService.settle(this.room.id, this.roundId, winnerIds, this.room.max_bet, !result.redeal); this.winners = active.filter((item) => winnerIds.includes(item.userId)).map((item) => ({ seatNumber: item.seatNumber, username: this.seats[item.seatNumber - 1]!.username, amount: settled.payouts.get(item.userId) ?? 0, handLabel: earlyWin ? "상대 전원 다이" : result.redeal ? "멍텅구리 구사 · 재경기" : result.handByUser.get(item.userId)!.label })); await pool.query("UPDATE game_rounds SET phase='RESULT',result_data=$2,settled_at=now() WHERE id=$1", [this.roundId, JSON.stringify({ winners: this.winners, redeal: result.redeal })]); await this.phaseTo("RESULT", RESULT_MS); for (const [userId, balance] of settled.balances) for (const socketId of this.participants.get(userId) ?? []) this.io.to(socketId).emit("wallet.updated", { balance }); }
}

export class SutdaRoomManager { private actors = new Map<string, SutdaRoomActor>(); constructor(private readonly io: GoldenServer) {} async initialize() { const recovered = await sutdaService.recoverInterruptedRounds(); if (recovered) console.warn(`Refunded ${recovered} interrupted Sutda round(s)`); const result = await pool.query<RoomRow>("SELECT id,game_type,code,name,min_bet,max_bet,enabled FROM game_rooms WHERE game_type='sutda' ORDER BY min_bet"); for (const row of result.rows) this.actors.set(row.id, new SutdaRoomActor(this.io, row)); } listRooms() { return [...this.actors.values()].map((actor) => actor.publicRoom()); } isParticipant(userId: string, roomId: string) { return this.actors.get(roomId)?.hasParticipant(userId) ?? false; } participantUserIds(roomId: string): string[] | null { return this.actors.get(roomId)?.participantUserIds() ?? null; } setPaused(roomId: string, value: boolean) { const actor = this.actors.get(roomId); if (!actor) return false; actor.setPaused(value); return true; } async join(socket: GoldenSocket, roomId: string) { const actor = this.actors.get(roomId); if (!actor?.room.enabled) throw new Error("ROOM_NOT_FOUND"); return actor.join(socket); } async leave(socket: GoldenSocket, roomId: string) { await this.actors.get(roomId)?.leave(socket); } async disconnect(socket: GoldenSocket) { for (const actor of this.actors.values()) if (actor.hasSocket(socket.id)) await actor.leave(socket); } async sit(userId: string, input: SutdaSeatCommand) { const actor = this.actors.get(input.roomId); if (!actor) throw new Error("ROOM_NOT_FOUND"); return actor.sit(userId, input); } async standUp(userId: string, roomId: string) { const actor = this.actors.get(roomId); if (!actor) throw new Error("ROOM_NOT_FOUND"); return actor.standUp(userId); } async setReady(userId: string, roomId: string, ready: boolean) { const actor = this.actors.get(roomId); if (!actor) throw new Error("ROOM_NOT_FOUND"); return actor.setReady(userId, ready); } async act(userId: string, input: SutdaActionCommand) { const actor = this.actors.get(input.roomId); if (!actor) throw new Error("ROOM_NOT_FOUND"); return actor.act(userId, input); } }
