import { useEffect, useMemo, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import { io, type Socket } from "socket.io-client";
import type { ClientToServerEvents, ServerToClientEvents, SutdaAction, SutdaRoomSnapshot, SutdaSeatSnapshot } from "@golden/contracts";
import { API_URL } from "../api";
import { Brand } from "../components/Brand";
import { ChipStack } from "../components/ChipStack";
import { GameShell } from "../components/GameShell";
import { HwatuCard } from "../components/HwatuCard";
import { OrientationGate } from "../components/OrientationGate";
import { RoomChat } from "../components/RoomChat";
import { SutdaHandGuide } from "../components/SutdaHandGuide";
import { randomRequestId } from "../lib/requestId";

const ACTION_SECONDS = 20;
const ANGLES = [90, 150, 210, 270, 330, 30];

export function SutdaRoomPage({ token, onLogout }: { token: string; onLogout: () => void }) {
  const { roomId = "" } = useParams(); const [snapshot, setSnapshot] = useState<SutdaRoomSnapshot | null>(null); const [message, setMessage] = useState(""); const [seconds, setSeconds] = useState(0); const [fullscreen, setFullscreen] = useState(false); const shellRef = useRef<HTMLDivElement>(null);
  const socket = useMemo<Socket<ServerToClientEvents, ClientToServerEvents>>(() => io(API_URL, { auth: { token }, autoConnect: false }), [token]);
  useEffect(() => { const accept = (next: SutdaRoomSnapshot) => setSnapshot((current) => !current || next.sequence >= current.sequence ? next : current); const connect = () => socket.emit("sutda.join", { roomId }, (ack) => ack.ok ? accept(ack.data) : setMessage(ack.error)); const wallet = ({ balance }: { balance: number }) => setSnapshot((current) => current ? { ...current, walletBalance: balance } : current); socket.on("connect", connect); socket.on("sutda.snapshot", accept); socket.on("wallet.updated", wallet); socket.on("connect_error", () => setMessage("게임 서버에 연결할 수 없습니다.")); socket.connect(); return () => { socket.emit("sutda.leave", { roomId }, () => undefined); socket.disconnect(); socket.off(); }; }, [roomId, socket]);
  useEffect(() => { const update = () => setSeconds(snapshot?.phaseEndsAt ? Math.max(0, Math.ceil((Date.parse(snapshot.phaseEndsAt) - Date.now()) / 1000)) : 0); update(); const id = window.setInterval(update, 250); return () => window.clearInterval(id); }, [snapshot?.phaseEndsAt]);
  useEffect(() => { const update = () => setFullscreen(document.fullscreenElement === shellRef.current); document.addEventListener("fullscreenchange", update); return () => document.removeEventListener("fullscreenchange", update); }, []);
  if (!snapshot) return <div className="loading-screen"><Brand /><p>{message || "섯다방에 연결하고 있습니다…"}</p></div>;
  const mine = snapshot.seats.find((seat) => seat.seatNumber === snapshot.mySeatNumber) ?? null; const myTurn = snapshot.actingSeat === snapshot.mySeatNumber; const seated = snapshot.seats.filter((seat) => seat.userId).length;
  const command = (action: SutdaAction) => { if (!snapshot.roundId) return; socket.emit("sutda.act", { requestId: randomRequestId(), roomId, roundId: snapshot.roundId, action }, (ack) => ack.ok ? setSnapshot(ack.data) : setMessage(ack.error)); };
  const sit = (seatNumber: number) => socket.emit("sutda.sit", { requestId: randomRequestId(), roomId, seatNumber }, (ack) => ack.ok ? setSnapshot(ack.data) : setMessage(ack.error));
  const ready = () => socket.emit("sutda.ready", { roomId, ready: !mine?.ready }, (ack) => ack.ok ? setSnapshot(ack.data) : setMessage(ack.error));
  const stand = () => socket.emit("sutda.standUp", { roomId }, (ack) => ack.ok ? setSnapshot(ack.data) : setMessage(ack.error));
  return <GameShell title={snapshot.room.name} subtitle={`삥 ${snapshot.room.minBet} · 최대 ${snapshot.room.maxBet} · 2–6인 PvP`} phaseLabel={snapshot.room.paused ? "일시정지" : label(snapshot)} phaseSeconds={snapshot.phaseEndsAt ? seconds : null} balance={snapshot.walletBalance} onLogout={onLogout} isFullscreen={fullscreen} onToggleFullscreen={() => void (document.fullscreenElement ? document.exitFullscreen() : shellRef.current?.requestFullscreen())} shellRef={shellRef}>
    <OrientationGate targetRef={shellRef} /><div className="room-shell"><section className="ot-stage"><div className="ot-felt sutda-felt"><div className="sutda-table"><div className="sutda-center"><strong>사인방 섯다</strong><span>팟 {snapshot.pot.amount.toLocaleString()}</span>{snapshot.street && <small>{snapshot.street === "first" ? "첫 패 베팅" : snapshot.street === "final" ? "둘째 패 베팅" : "패 공개"}</small>}</div>{ordered(snapshot.seats, snapshot.mySeatNumber).map(({ seat, angle }) => <Seat key={seat.seatNumber} seat={seat} angle={angle} canSit={!mine && !seat.userId} onSit={() => sit(seat.seatNumber)} />)}</div>{myTurn && mine && <div className="sutda-actions on-felt"><span>콜 {snapshot.toCall.toLocaleString()}</span><button className="outline-button bj-act-surrender" onClick={() => command("die")}>다이</button>{snapshot.toCall === 0 ? <button className="outline-button bj-act-stand" onClick={() => command("check")}>체크</button> : <button className="outline-button bj-act-double" onClick={() => command("call")}>콜</button>}<button className="outline-button bj-act-hit" onClick={() => command("half")}>하프</button><b>{seconds}s</b></div>}{mine && snapshot.room.phase === "WAITING" && <div className="holdem-ready-dock on-felt"><span className="holdem-ready-status">{snapshot.seats.filter((seat) => seat.ready && seat.userId).length}/{seated}명 준비 완료</span><button className="outline-button bj-act-hit" onClick={ready}>{mine.ready ? "준비 취소" : "준비 완료"}</button></div>}{message && <p className="ot-message">{message}</p>}</div>{/* No footer rail — secondary controls float over the felt like the other two poker rooms. */}{mine && <button className="outline-button game-fab fab-slot-2" onClick={stand} disabled={Boolean(snapshot.roundId && !mine.folded)}>자리 비우기</button>}<SutdaHandGuide className="game-fab fab-slot-1" /><RoomChat socket={socket} roomId={roomId} token={token} /></section></div>
  </GameShell>;
}

function ordered(seats: SutdaSeatSnapshot[], mine: number | null) { const rotate = mine ? mine - 1 : 0; return seats.map((seat, index) => ({ seat, angle: ANGLES[(index - rotate + seats.length) % seats.length]! })); }
function Seat({ seat, angle, canSit, onSit }: { seat: SutdaSeatSnapshot; angle: number; canSit: boolean; onSit: () => void }) { const radius = 42, x = 50 + radius * Math.cos(angle * Math.PI / 180), y = 50 + radius * Math.sin(angle * Math.PI / 180) * .72; const style = { left: `${x}%`, top: `${y}%` }; if (!seat.userId) return canSit ? <button className="holdem-seat holdem-seat-empty" style={style} onClick={onSit}>착석</button> : <div className="holdem-seat holdem-seat-empty" style={style} />; return <div className={`holdem-seat sutda-seat ${seat.isTurn ? "is-turn" : ""} ${seat.folded ? "is-folded" : ""}`} style={style}><div className="sutda-cards">{seat.cards ? seat.cards.map((card) => <HwatuCard key={card.id} card={card} />) : <><HwatuCard hidden /><HwatuCard hidden /></>}</div><div className="holdem-seat-name">{seat.isDealer && <span className="holdem-button-chip">D</span>}{seat.username}</div><div className="holdem-seat-stack">{seat.stack.toLocaleString()}</div><ChipStack amount={seat.totalContributed} label="베팅" />{seat.folded && <div className="holdem-seat-status fold">다이</div>}{seat.handLabel && !seat.folded && <div className="holdem-seat-status live">{seat.handLabel}</div>}</div>; }
function label(snapshot: SutdaRoomSnapshot) { if (snapshot.room.phase === "PLAYER_TURN") return "베팅 진행 중"; if (snapshot.room.phase === "DEALING") return "패 배분"; if (snapshot.room.phase === "RESULT") return "승부 결과"; return "플레이어 대기"; }
